################### DataSource Configuration ##########################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: CatHikariCP
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
      validation-timeout: 5000