################### Service Configuration ##########################
service:
  mapserver: localhost:8080
  geoserver: localhost:8888
  tiledata: /home/dev/data/tile
################### OSS Configuration ##########################
oss:
  accessKeyId: LTAIelgAxlE5sJMB
  accessKeySecret: RE0tSBGvQjD7EkCNILYfSqC7JGArn3
  endpoint: oss-cn-beijing-internal.aliyuncs.com
  bucket: cateye-tile
################### DEM Data ##########################
dem:
  gujiao: /home/dev/data/gujiao.tif
  jingzhuang: /home/dev/data/jzhdem_7m.tif