################### Service Configuration ##########################
service:
  mapserver: localhost:8080
  geoserver: localhost:8888
  tiledata: F:/BaiduNetdiskDownload
################### OSS Configuration ##########################
oss:
  accessKeyId: LTAIelgAxlE5sJMB
  accessKeySecret: RE0tSBGvQjD7EkCNILYfSqC7JGArn3
  endpoint: oss-cn-beijing.aliyuncs.com
  bucket: cateye-tile
################### DEM Data ##########################
dem:
  gujiao: e:/data/gujiao.tif
  jingzhuang: e:/data/jzhdem_7m.tif