################### 应用配置
info:
  version: 0.0.1
  name: ${spring.application.name}
  comment: "配置中心"
################### 数据库连接池配置 Postgresql + Hikari
spring:
  cloud:
    config:
      server:
        jdbc:
          sql: select key,value from t_application_properties where application=? and profile=? and label=? order by key
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: Cateye@2018
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: CatbookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000